// <auto-generated />
using System;
using GDFHRMS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GDFHRMS.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20210128212707_AddedTwoTables")]
    partial class AddedTwoTables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("GDFHRMS.Models.Dtos.Employee_AddressDto", b =>
                {
                    b.Property<int>("Address_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Address_area")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address_country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address_lot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address_region")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address_street")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address_townVillage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Employee_Id")
                        .HasColumnType("int");

                    b.HasKey("Address_Id");

                    b.ToTable("Employee_Address");
                });

            modelBuilder.Entity("GDFHRMS.Models.Dtos.Employee_Personal_InformationDto", b =>
                {
                    b.Property<int>("Employee_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Employee_contractNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("Employee_dob")
                        .HasColumnType("datetime2");

                    b.Property<string>("Employee_firstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Employee_lastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Employee_nationalIdNumber")
                        .HasColumnType("int");

                    b.Property<int>("Employee_nationality_id")
                        .HasColumnType("int");

                    b.Property<string>("Employee_otherName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Employee_passportExpirationNumber")
                        .HasColumnType("datetime2");

                    b.Property<string>("Employee_passportNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Employee_regimentNumber")
                        .HasColumnType("int");

                    b.Property<string>("Employee_sex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Employee_tinNumber")
                        .HasColumnType("int");

                    b.Property<string>("Employee_title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ethnicity_id")
                        .HasColumnType("int");

                    b.Property<int>("MaritalStatus_id")
                        .HasColumnType("int");

                    b.Property<int>("Religion_id")
                        .HasColumnType("int");

                    b.HasKey("Employee_id");

                    b.ToTable("Employee_Personal_Information");
                });

            modelBuilder.Entity("GDFHRMS.Models.Dtos.NationalParkDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Established")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("NationalParks");
                });
#pragma warning restore 612, 618
        }
    }
}
